[package]
name = "nalu_coin"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "dna/zomes/coordinator",
  "dna/zomes/integrity",
]

[dependencies]
hdk = "=0.5.0-dev.19"
serde = "1"
nalu_coin_integrity = { path = "dna/zomes/integrity" }

[lib]
name = "nalu_coin"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true